apiVersion: v1
kind: Secret
metadata:
  name: remi-secrets
  namespace: remi
type: Opaque
stringData:
  jwt-secret: your-super-secret-jwt-key-change-in-production
  mongo-root-username: admin
  mongo-root-password: password123
  mongo-uri-auth: mongodb://admin:password123@mongo-service:27017/remi-auth?authSource=admin
  mongo-uri-catalog: mongodb://admin:password123@mongo-service:27017/remi-catalog?authSource=admin
  mongo-uri-cart: mongodb://admin:password123@mongo-service:27017/remi-cart?authSource=admin
  mongo-uri-checkout: mongodb://admin:password123@mongo-service:27017/remi-checkout?authSource=admin

